Vagrant.configure("2") do |config|

config.vm.boot_timeout = 600
  config.vm.define "web" do |web|
    web.vm.box = "puphpet/centos64-x64"
    web.vm.hostname = 'web'
    web.vm.box_url = "puphpet/centos64-x64"

    web.vm.network :private_network, ip: "192.168.99.101"
    web.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    
    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web"]
      
    web.vm.provision :shell, :path => "setup_web.sh"
        
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "puphpet/centos64-x64"
    db.vm.hostname = 'db'
    db.vm.box_url = "puphpet/centos64-x64"

    db.vm.network :private_network, ip: "192.168.99.104"
    
    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "db"]
    end
  end
  
  config.vm.define "cache1" do |cache1|
    cache1.vm.box = "puphpet/centos64-x64"
    cache1.vm.hostname = 'cache'
    cache1.vm.box_url = "puphpet/centos64-x64"

    cache1.vm.network :private_network, ip: "192.168.99.103"
    cache1.vm.network :forwarded_port, guest: 6379, host: 10322, id: "cache1"
    
    cache1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "cache1"]
    
    cache1.vm.provision :shell, :path => "setup_redis.sh"
     
      
    end
  end
  
  config.vm.define "apps" do |apps|
    apps.vm.box = "puphpet/centos64-x64"
    apps.vm.hostname = 'apps'
    apps.vm.box_url = "puphpet/centos64-x64"

    apps.vm.network :private_network, ip: "192.168.99.102"
    apps.vm.network :forwarded_port, guest: 22, host: 10522, id: "ssh"

    apps.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "apps"]
      
    apps.vm.provision :shell, :path => "setup_webapps.sh"
    end
  end
  
end 
