# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.box = "hashicorp/precise64"
    web.vm.network "private_network", ip: "192.168.99.101"
    web.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx ufw
      sudo service nginx restart
      sudo ufw default deny incoming
      sudo ufw default allow outgoing
      sudo ufw allow ssh
      sudo ufw allow 80
      sudo ufw --force enable
    SHELL
  end

  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.box = "hashicorp/precise64"
    app.vm.network "private_network", ip: "192.168.99.102"
    app.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install curl ufw -y
      curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
      sudo apt-get install -y nodejs ufw
      npm install -g express-generator
      express hooq
      cd hooq
      npm install
      npm start &
      sudo ufw default deny incoming
      sudo ufw default allow outgoing
      sudo ufw allow ssh
      sudo ufw allow 3000
      sudo ufw --force enable
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.box = "hashicorp/precise64"
    db.vm.network "private_network", ip: "192.168.99.104"
    db.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y postgresql ufw
      sudo echo "listen_addresses = '192.168.99.104'" >> /etc/postgresql/9.1/main/postgresql.conf
      sudo echo "host  all  all 0.0.0.0/0 trust" >> /etc/postgresql/9.1/main/pg_hba.conf
      sudo service postgresql restart
      sudo ufw default deny incoming
      sudo ufw default allow outgoing
      sudo ufw allow 5432
      sudo ufw --force enable
    SHELL
  end

  config.vm.define "cache" do |cache|
    cache.vm.hostname = "cache"
    cache.vm.box = "hashicorp/precise64"
    cache.vm.network "private_network", ip: "192.168.99.103"
    cache.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ufw make
      wget http://download.redis.io/releases/redis-3.0.7.tar.gz
      tar xzvf redis-3.0.7.tar.gz
      cd redis-3.0.7
      make
      sed -i -- 's/127.0.0.1/192.168.99.103/g' redis.conf
      sed -i -- 's/daemonize no/daemonize yes/g' redis.conf
      src/redis-server redis.conf &
      ufw default deny incoming
      ufw default allow outgoing
      ufw allow 6379
      ufw --force enable
    SHELL
  end
end
