---
- hosts: db
  user: vagrant

  tasks:
    - name: set locale
      shell: export LC="en_US.UTF-8" && export LANGUAGE="en_US.UTF-8" && locale >> /etc/environment
 
    - name: Update apt cache
      apt: update-cache=yes

    - name: Install system packages
      apt: pkg={{ item }}
      with_items:
        - postgresql
        - openssh-server
        - libpq-dev
        - python-psycopg2

- hosts: db
  user: vagrant
  gather_facts: no
  become: yes
  become_user: postgres

  vars:
    dbname: myapp
    dbuser: myapp
    dbpassword: password

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  # handlers:
  #   - name: restart nginx
  #     service: name=nginx state=restarted

# vim:ft=ansible: