---
- hosts: web
  user: vagrant

  tasks:
    - name: set locale
      shell: export LC_ALL="en_US.UTF-8" && export LANGUAGE="en_US.UTF-8" && locale >> /etc/environment
 
    - name: Update apt cache
      apt: update-cache=yes

    - name: Install system packages
      apt: pkg={{ item }}
      with_items:
        - nginx
        - openssh-server
        - ufw

    - name: copy reverse proxy for nginx config
      template: src=files/default.j2 dest=/etc/nginx/sites-available/default

    - name: restart nginx
      service: name=nginx state=restarted

# vim:ft=ansible: